version: '3.9'

# T25 — Docker Compose for local dev
# - Postgres database
# - Backend (Node placeholder)
# - Frontend (Next placeholder)
# - Localstack (optional S3-compatible services)

services:
  db:
    image: postgres:15
    container_name: tapne_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tapne
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: node:18-alpine
    container_name: tapne_backend
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tapne
      JWT_SECRET: dev-secret
      MEDIA_CDN_URL: http://localhost:8080
      S3_ENDPOINT: http://localstack:4566
      S3_BUCKET: tapne
    command: sh -lc "npm --prefix backend run start:dev"
    ports:
      - "3001:3001"

  frontend:
    image: node:18-alpine
    container_name: tapne_frontend
    depends_on:
      - backend
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
    command: sh -lc "npm --prefix frontend/web run dev"
    ports:
      - "3000:3000"

  # Optional: localstack for S3/Cognito/etc. Only S3 is referenced here.
  localstack:
    image: localstack/localstack:1.4
    container_name: tapne_localstack
    environment:
      SERVICES: s3
      DEBUG: "1"
      AWS_DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  db_data:
  localstack_data:

